channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==2.2.1
  - futures==3.0.5
  - numpy==1.26.4
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
